

--Q1. What is the total revenue generated by male vs. female customers?

select gender,sum(purchase_amount) as total_revenue
from customer_behavior
group by gender;

--Q2. Which customers used a discount but still spent more than the average purchase amount? 

select customer_id,purchase_amount from customer_behavior where purchase_amount > (select AVG(purchase_amount) 
from customer_behavior) and 
discount_applied = 'Yes';

-- Q3. Which are the top 5 products with the highest average review rating?

with cte as
(select item_purchased,avg(review_rating) as avg_rating,
rank() over (order by avg(review_rating)desc) as rnk
from customer_behavior
group by item_purchased)

select * from cte where rnk<=5;

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 

select shipping_type,avg(purchase_amount) as avg_purchase from customer_behavior
where shipping_type in ('Standard','Express')
group by shipping_type;


--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.

select subscription_status,count(customer_id) as total_customer,
cast(avg(purchase_amount)as decimal(10,2)) as avg_spend,cast(sum(purchase_amount) as decimal(10,2)) as total_spend from customer_behavior
group by subscription_status;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?

select top 5 item_purchased , cast(sum(case when discount_applied = 'yes' then 1 else 0 end) * 100.0/count(*) as decimal(5,2))
as discount_rate from customer_behavior
group by item_purchased
order by discount_rate desc;

--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 

with cte as (
select customer_id,previous_purchases,
case 
	when previous_purchases = 1 then 'New'
	when previous_purchases between 2 and 10 then 'Returning'
	else 'loyal'
	end as customer_segment
from customer_behavior
)

select customer_segment,count(*) as customer_label
from cte
group by customer_segment;


--Q8. What are the top 3 most purchased products within each category? 

with cte as
(select category,item_purchased,count(customer_id) total_order,
row_number() over (partition by category order by count(customer_id)) as rnk
from customer_behavior
group by category,item_purchased
)
select category,item_purchased,rnk,total_order from cte
where rnk<=3
order by total_order desc

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select subscription_status , count(customer_id) repeat_buyers from customer_behavior where previous_purchases > 5
group by subscription_status

--Q10. What is the revenue contribution of each age group? 

select age_group,sum(purchase_amount) total_revenue from customer_behavior
group by age_group
order by total_revenue desc







